apiVersion: v1
kind: ConfigMap

metadata:
  name: revenda-config
  namespace: revenda

data:
  POSTGRES_DB: revenda
  POSTGRES_HOST: postgres-service

  DATABASE_URL: postgresql://admin:admin@postgres-service:5432/revenda
