apiVersion: v1
kind: Service

metadata:
  name: revenda-api-service
  namespace: revenda


spec:

  type: NodePort


  selector:
    app: revenda-api


  ports:

    - port: 8000

      targetPort: 8000

      nodePort: 30080
